=== IRNAS/KORUZA/instructions/instructions_koruza-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1">

  <xs:element name="instructions" type="typeInstructions"/>
  <xs:complexType name="typeInstructions">
     <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="image" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="video" type="typeVideo" minOccurs="0"/>
            <xs:element name="physic_parts" type="typePhysic_parts" minOccurs="0"/>
            <xs:element name="system_steps" type="typeSystem_steps" minOccurs="0"/>

     </xs:sequence>
  </xs:complexType>

    <xs:complexType name="typeSystem_steps">
        <xs:all>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="video" type="typeVideo" minOccurs="0"/>
            <xs:element name="image" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="logic_parts" type="typeLogic_parts" minOccurs="0"/>
            <xs:element name="steps" type="typeSteps" minOccurs="0"/>
            <xs:element name="module_steps" type="typeModule_steps"  maxOccurs="unbounded"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="typeModule_steps">
        <xs:all>
            <xs:element name="module" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="video" type="typeVideo" minOccurs="0"/>
            <xs:element name="image" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="logic_parts" type="typeLogic_parts" minOccurs="0"/>
            <xs:element name="steps" type="typeSteps" minOccurs="0"/>
            <xs:element name="sub_module_steps" type="typeSub_module_steps"  maxOccurs="unbounded"/>
        </xs:all>
        <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    <xs:complexType name="typeSub_module_steps">
        <xs:all>
            <xs:element name="sub_module" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="video" type="typeVideo" minOccurs="0"/>
            <xs:element name="image" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="logic_parts" type="typeLogic_parts" minOccurs="0"/>
            <xs:element name="steps" type="typeSteps" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    <xs:complexType name="typeSteps">
        <xs:all>
            <xs:element name="step" type="typeStep" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="typeStep">
        <xs:all>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="video" type="typeVideo" minOccurs="0"/>
            <xs:element name="image" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="step_parts" type="typeStep_parts" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <xs:complexType name="typeStep_parts">
        <xs:sequence>
            <xs:element name="step_part" type="typeStep_part"  maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="typeStep_part">
        <xs:all>
            <xs:element name="part" type="xs:positiveInteger"/>
            <xs:element name="quantity" type="xs:positiveInteger" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
    </xs:complexType>


    <xs:complexType name="typeVideo">
        <xs:all>
            <xs:element name="description" type="xs:token" minOccurs="0"/>
            <xs:element name="url" type="xs:normalizedString" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="typeLogic_parts">
        <xs:sequence>
            <xs:element name="logic_part" type="typeLogic_part" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="typeLogic_part">
        <xs:all>
            <xs:element name="part_name" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="quantity" type="xs:positiveInteger" minOccurs="0"/>
            <xs:element name="schematic_id" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="image" type="xs:normalizedString" minOccurs="0"/>
            <xs:element name="options" type="typeOptions" minOccurs="0"/>
            <xs:element name="file" type="typeFile" minOccurs="0" maxOccurs="unbounded"/>

        </xs:all>
        <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    <xs:complexType name="typeOptions">
        <xs:sequence>
            <xs:element name="option" type="typeOption" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="typeOption">
        <xs:all>
            <xs:element name="part_name" type="xs:string" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="typePhysic_parts">
        <xs:sequence>
            <xs:element name="physic_parts_list" type="typePhysic_parts_list" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="typePhysic_parts_list">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="physic_part" type="typePhysic_part" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="typePhysic_part">
        <xs:all>
            <xs:element name="description" type="xs:string"  minOccurs="0"/>
            <xs:element name="part_name" type="xs:string"/>
            <xs:element name="quantity" type="xs:string" minOccurs="0"/>
            <xs:element name="phy_part" type="xs:string"  minOccurs="0"/>
            <xs:element name="supplier" type="xs:string"  minOccurs="0"/>
            <xs:element name="net3" type="xs:string"  minOccurs="0"/>
            <xs:element name="file" type="typeFile" minOccurs="0" maxOccurs="unbounded"/>
        </xs:all>
        <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="typeFile">
                    <xs:element name="url" type="xs:normalizedString"/>
    </xs:complexType>

</xs:schema>

=== IRNAS/KORUZA/instructions/instructions_koruza.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="instructions_koruza.xsl"?>
<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="instructions_koruza-schema.xsd">

<name>INSTRUCTIONS KORUZA</name>
<description>How to assemble the system...General instructions and pointers.</description>
<video>
  	<description>Intro video</description>
        <url>http://www.youtube.com/embed/yq6hBNCzH10</url>

</video>

<system_steps>
  <description>Here we explain how to put all modules together...</description>
  <steps>
    <step order="1">
      <description>Step one...</description>
    </step>
    <step order="2">
      <description>Step two...</description>
    </step>
  </steps>
  
  <module_steps order="1">
    <module> LEGAL</module>
    <description>Here we explain how to assamble the first module from its sub-modules</description>
  </module_steps>
  
  <module_steps order="2">
    <module> OPTICAL - DATA</module>
    <description>Here we explain how to assamble the first module from its sub-modules</description>
    <steps>
      <step order="1">
        <description>Step one...</description>
      </step>
      <step order="2">
        <description>Step two...</description>
      </step>
    </steps>
    
    <sub_module_steps order="1">
      <sub_module> TRANSCEIVER</sub_module>
      <description>Here we explain how to assamble fist sub-module of the optical-data module.</description>
      <steps>
        <step order="1">
          <description>Step one...</description>

        </step>
        <step order="2">
          <description>Step two...</description>
        </step>
      </steps>
      
      <logic_parts>
           <logic_part order="1">
             <part_name>SFP module A</part_name>
             <description>SFP 1.25G BIDI Tx1310/Rx1550nm 40km SC Connector DDM Extended temperature range</description>
             <quantity>1</quantity>
             <options>
               <option> <part_name/> </option>
             </options>
           </logic_part>

           <logic_part order="2">
             <part_name>SFP module B</part_name>
             <description>SFP 1.25G BIDI Tx1550/Rx1310nm 40km SC Connector DDM Extended temperature range</description>
             <quantity>1</quantity>
             <options>
               <option> <part_name/> </option>
             </options>
           </logic_part>

           <logic_part order="3">
             <part_name>Alu mount</part_name>
             <description>Precise aluminium mounting piece acting as a heat-sink2</description>
             <quantity>2</quantity>
             <options>
               <option> <part_name/> </option>
             </options>
           </logic_part>



         </logic_parts>
    </sub_module_steps>
    
    <sub_module_steps order="2">
      <sub_module> COLLIMATION OPTICS</sub_module>
      <description>Here we explain how to assamble the sub-module of the optical-data module.</description>
      <steps>
        <step order="1">
          <description>Step one...</description>
        </step>
        <step order="2">
          <description>Step two...</description>
        </step>
      </steps>
      
      <logic_parts>
           <logic_part order="1">
             <part_name>Plano-convex lens</part_name>
             <description>50mm round plano-covex lens F=100mm.</description>
             <quantity>2</quantity>
             <options>
               <option> <part_name/> </option>
             </options>
           </logic_part>

      </logic_parts>
    </sub_module_steps>
    
    <sub_module_steps order="3">
      <sub_module> SFP MONITORING</sub_module>
      <description>Here we explain how to assamble the sub-module of the optical-data module.</description>
      <steps>
        <step order="1">
          <description>Get Koruza SFP extension PCB panel consisting of two larger SFP socket boards and three smaller SFP plug boards.</description>
          <image>img/img2_3_1.jpg</image>
                  <step_parts>
            <step_part order="1">
              <part>1</part>
              <quantity>2</quantity>
            </step_part>
            <step_part order="2">
              <part>2</part>
              <quantity>2</quantity>
            </step_part>
            <step_part order="3">
              <part>10</part>
              <quantity>0</quantity>
            </step_part>
            <step_part order="4">
              <part>11</part>
              <quantity>0</quantity>
            </step_part>
            <step_part order="5">
              <part>12</part>
              <quantity>0</quantity>
            </step_part>
          </step_parts>
        </step>
        <step order="2">
          <description>Solder the SFP socket to the boards, make sure it is oriented correctly, with the notch away from the rest of connectors.</description>
          <image>img/img2_3_2.jpg</image>
                  <step_parts>
            <step_part order="1">
              <part>1</part>
              <quantity>2</quantity>
            </step_part>
            <step_part order="2">
              <part>9</part>
              <quantity>2</quantity>
            </step_part>
          </step_parts>
        </step>
		<step order="3">
          <description>Solder the SATA connector to SFP socket boards, make sure to solder the mounting legs as well.</description>
          <image>img/img2_3_3.jpg</image>
        	  <step_parts>
            <step_part order="1">
              <part>1</part>
              <quantity>2</quantity>
            </step_part>
            <step_part order="2">
              <part>7</part>
              <quantity>2</quantity>
            </step_part>
          </step_parts>
        </step>
		<step order="4">
          <description>Solder the SATA connector to SFP plug boards, make sure to solder the mounting legs as well.</description>
          <image>img/img2_3_4.jpg</image>
        	  <step_parts>
            <step_part order="1">
              <part>2</part>
              <quantity>2</quantity>
            </step_part>
            <step_part order="2">
              <part>7</part>
              <quantity>2</quantity>
            </step_part>
          </step_parts>
        </step>
		<step order="5">
          <description>Solder the SFP cage to SFP socket boards.</description>
          <image>img/img2_3_5.jpg</image>
        	  <step_parts>
            <step_part order="1">
              <part>2</part>
              <quantity>2</quantity>
            </step_part>
            <step_part order="2">
              <part>8</part>
              <quantity>2</quantity>
            </step_part>
          </step_parts>
        </step>
		<step order="6">
          <description>Solder IDC connectors to the boards, ckeck their orientation before soldering!</description>
          <image>img/img2_3_6.jpg</image>
        	  <step_parts>
            <step_part order="1">
              <part>1</part>
              <quantity>2</quantity>
            </step_part>
			<step_part order="2">
              <part>2</part>
              <quantity>2</quantity>
            </step_part>
            <step_part order="3">
              <part>3</part>
              <quantity>6</quantity>
            </step_part>
          </step_parts>
        </step>
		<step order="7">
          <description>3D print a sleeve for the SFP extension plug</description>
          <image>img/img2_3_7.jpg</image>
                  <step_parts>
            <step_part order="1">
              <part>2</part>
              <quantity>2</quantity>
            </step_part>
          </step_parts>
        </step>
		<step order="8">
          <description>Connect the SFP socket and plug board with SATA cable.</description>
          <image>img/img2_3_8.jpg</image>
                  <step_parts>
            <step_part order="1">
              <part>1</part>
              <quantity>2</quantity>
            </step_part>
			<step_part order="2">
              <part>2</part>
              <quantity>2</quantity>
            </step_part>
            <step_part order="3">
              <part>6</part>
              <quantity>2</quantity>
            </step_part>
          </step_parts>
        </step>
		<step order="9">
          <description>Assemble 20cm long IDC 10 cables.</description>
          <image>img/img2_3_9.jpg</image>
                  <step_parts>
            <step_part order="1">
              <part>3</part>
              <quantity>4</quantity>
            </step_part>
			<step_part order="2">
              <part>5</part>
              <quantity>2</quantity>
            </step_part>
          </step_parts>
        </step>
		<step order="10">
          <description>Connect SFP socket and plug boards with the IDC cable.</description>
          <image>img/img2_3_10.jpg</image>
                  <step_parts>
            <step_part order="1">
              <part>1</part>
              <quantity>2</quantity>
            </step_part>
			<step_part order="2">
              <part>2</part>
              <quantity>2</quantity>
            </step_part>
          </step_parts>
        </step>
      </steps>
      
      <logic_parts>
          <logic_part order="1">
             <part_name>Socket PCB</part_name>
             <description>SFP extension PCB</description>
             <quantity>2</quantity>
             <options>
               <option> <part_name/> </option>
             </options>
           </logic_part>

           <logic_part order="2">
             <part_name>Plug SFP</part_name>
             <description>SFP extension PCB</description>
             <quantity>2</quantity>
             <options>
               <option> <part_name/> </option>
             </options>
           </logic_part>

           <logic_part order="3">
             <part_name>IDC 10 connector receptacle</part_name>
